### ISSUE TITLE
Locked / hidden achievement counter

### ISSUE THREAD

**Issue by Ash258** [Outsetini/Air-Classic#12]
There is only one thing, that i miss in your great skin.**Hidden achievement counter as in normal steam skin.**

![image](https://user-images.githubusercontent.com/13260377/27254220-8c65a084-5384-11e7-91f0-6acd02452619.png)

**Comment by Outsetini** [comment]
The "View all achievements" button should take you to the page that lists all the locked achievements. The button on the right side was hidden since there wasn't an easy way to have it match the theme.
