### ISSUE TITLE
Fix for constant High CPU usage.

### ISSUE THREAD

**Issue by Inrixia** [Outsetini/Air-Classic#13]
So for a while Air-Classic has been causing high cpu usage RE this post: https://steamcommunity.com/groups/airforsteam/discussions/1/2906376154332791499/

For me it was upwards of 14-16% cpu usage 24/7 if steam was open, for a friend it was over 40% at times forcing him to stop using the skin. But I love air so I kept on stubbornly using it. However today I decided to just look into the files and figure out what was causing the issue to try to fix it.

The file causing the issue is: "/Resource/layout/steamrootdialog.layout/", Line 220, if "fullscreen" and "add_game" exist.

Just removing them works but causes other issues, but creating a new hidden region and placing them inside that fixes the issue.

Here is the updated file that I'm using with  the modified code: https://pastebin.com/raw/yQK020y3

Hope this helps :)

PS: There is a bit more info in the post I just did in the above steam discussion if you want to go read that.

**Comment by Outsetini** [comment]
Thanks for the link, I've got this patched up and will be pushing out an update soon!

3493741cb2c40a496c7917aeed5122fc0340119b
