### ISSUE TITLE
Online status options not working in the steam logo dropdown

### ISSUE THREAD

**Issue by Desidiosus** [Outsetini/Air-Classic#15]
The `Online` and `Away` options in the Steam logo dropdown menu don't seem to do anything. They simply get checked but do not actually affect the online status and you can have them both checked at once. There used to be an `Offline` option as well but it is completely missing. It seems to be replaced by `Invisible`.

**Comment by Outsetini** [comment]
Good catch, I forgot to remove those. They are no obsolete with the new chat ui update.
