### ISSUE TITLE
Black bar on the side of main page

### ISSUE THREAD

**Issue by AnimePrince** [outsetini/Air-Classic#6]
![vjia5brtx](https://cloud.githubusercontent.com/assets/16970032/12694212/7d8c0bbc-c6da-11e5-8c3d-2f018cc72316.jpg)

Picture is a example of what I'm talking about. It goes away when I click the x, but then it leaves the pages a little bit misaligned.

**Comment by outsetini** [comment]
Should be fixed with the latest version on the master branch, let me know if it's still an issue for you!
